config/routes.rb
NewIsland::Application.routes.draw do

  resources :villages

  devise_for :users
  resources :users, :only => [:index, :show]
  resources :villages
  match "villages/:id/upgrade_hq" => 'villages#upgrade_hq', :controller => 'villages', :action => 'upgrade_hq'
  match "villages/:id/upgrade_depot" => 'villages#upgrade_depot', :controller => 'villages', :action => 'upgrade_depot'
  match "villages/:id/upgrade_woodhouse" => 'villages#upgrade_woodhouse', :controller => 'villages', :action => 'upgrade_woodhouse'
  match "villages/:id/upgrade_pit" => 'villages#upgrade_pit', :controller => 'villages', :action => 'upgrade_pit'
  match "villages/:id/upgrade_mine" => 'villages#upgrade_mine', :controller => 'villages', :action => 'upgrade_mine'
  match "villages/:id/upgrade_farm" => 'villages#upgrade_farm', :controller => 'villages', :action => 'upgrade_farm'
  match "coordinates/map" => 'coordinates#map', :controller => 'coordinates' 
  match "coordinates/up_to_top" => 'coordinates#up_to_top', :controller => 'coordinates', :action => 'up_to_top'
  match "coordinates/up_to_bottom" => 'coordinates#up_to_bottom', :controller => 'coordinates', :action => 'up_to_bottom'
  match "coordinates/up_to_right" => 'coordinates#up_to_right', :controller => 'coordinates', :action => 'up_to_right'
  match "coordinates/up_to_left" => 'coordinates#up_to_left', :controller => 'coordinates', :action => 'up_to_left'
  
  match "villages/:id/ressources" => 'villages#ressources', :controller => 'villages', :action => 'ressources'
root :to => "pages#home"
end

app/views/pages/home.html.erb
<table class="home">
  <tr>
	<td class="main">
      
      <h1>Browsergame Test</h1>
	</td>
  </tr>
  <tr>
  <td>
  </td>
  <td class="sidebar round">   
    <h3>Log in</h3>
  	  <% if signed_in? %>
	    Hey! <br/>
	  	Du bist bereits eingeloggt<br />
	  	<%= link_to "Link zu deinem Profil", current_user %>
	  	<% else %>
	    <%= form_for("user", :url => user_session_path) do |f| %>
		Email:
  		<%= f.text_field :email %>
  		Passwort:
  		<%= f.password_field :password %>
  		<%= f.check_box :remember_me %> dauerhaft einloggen
  		<%= f.submit 'Einloggen' %> <br/><br/>
  		<%= link_to "Passwort vergessen?", new_password_path('user') %>
	  <% end %>
	<% end %>
    </td>
  </tr>
</table>

app/views/pages/map.html.erb
<% x = Coordinates.where(:user_id => current_user.id).first.x - 3 %>
<% y = Coordinates.where(:user_id => current_user.id).first.y + 3 %>

<center
<div class = "map">
<table cellspacing="0" cellpadding="0">

  <% while y  > Coordinates.where(:user_id => current_user.id).first.y - 4 %>
    <tr>
      <% while x  < Coordinates.where(:user_id => current_user.id).first.x + 5 %> 
        <% if Village.where(:x => x , :y => y).empty? %>
          <td> <%= image_tag("wiese.png") %> </td>
          <% x = x + 1 %>
        <% else %>
          <td> 1 </td>
          <% x = x + 1 %>
        <% end %>
      <% end %>
    </tr>
    <% y = y - 1 %>
    <% x = Coordinates.where(:user_id => current_user.id).first.x - 3 %>
  <% end %>

</table>
</div>
</center>