config/routes.rb
NewIsland::Application.routes.draw do

  resources :villages

  devise_for :users
  resources :users, :only => [:index, :show]
  resources :villages
  match "villages/:id/upgrade_hq" => 'villages#upgrade_hq', :controller => 'villages', :action => 'upgrade_hq'
  match "villages/:id/upgrade_depot" => 'villages#upgrade_depot', :controller => 'villages', :action => 'upgrade_depot'
  match "villages/:id/upgrade_woodhouse" => 'villages#upgrade_woodhouse', :controller => 'villages', :action => 'upgrade_woodhouse'
  match "villages/:id/upgrade_pit" => 'villages#upgrade_pit', :controller => 'villages', :action => 'upgrade_pit'
  match "villages/:id/upgrade_mine" => 'villages#upgrade_mine', :controller => 'villages', :action => 'upgrade_mine'
  match "villages/:id/upgrade_farm" => 'villages#upgrade_farm', :controller => 'villages', :action => 'upgrade_farm'
  match "coordinates/map" => 'coordinates#map', :controller => 'coordinates' 
  match "coordinates/up_to_top" => 'coordinates#up_to_top', :controller => 'coordinates', :action => 'up_to_top'
  match "coordinates/up_to_bottom" => 'coordinates#up_to_bottom', :controller => 'coordinates', :action => 'up_to_bottom'
  match "coordinates/up_to_right" => 'coordinates#up_to_right', :controller => 'coordinates', :action => 'up_to_right'
  match "coordinates/up_to_left" => 'coordinates#up_to_left', :controller => 'coordinates', :action => 'up_to_left'
  
  match "villages/:id/ressources" => 'villages#ressources', :controller => 'villages', :action => 'ressources'
root :to => "pages#home"
end

app/models/village.rb
class Village < ActiveRecord::Base
has_many :pits
has_many :woodhouses
has_many :mines
has_many :hqs
has_many :depots
has_many :farms
has_many :coordinates



  def update_population
    update_attribute(:population, Pit.find(pit_id).worker + Woodhouse.find(woodhouse_id).worker +
    Mine.find(mine_id).worker + Hq.find(hq_id).worker + Depot.find(depot_id).worker)
  end
  
  def upgrade_hq
    update_attribute(:hq_id, hq_id + 1)
    update_attribute(:wood, wood - Hq.find(hq_id).woodcost)
    update_attribute(:stone, stone - Hq.find(hq_id).stonecost)
    update_attribute(:iron, iron - Hq.find(hq_id).ironcost)
  end
 

  def upgrade_depot
    update_attribute(:depot_id, depot_id + 1)
    update_attribute(:wood, wood - Depot.find(depot_id).woodcost)
    update_attribute(:stone, stone - Depot.find(depot_id).stonecost)
    update_attribute(:iron, iron - Depot.find(depot_id).ironcost)
  end
  
  def upgrade_woodhouse
    update_attribute(:woodhouse_id, woodhouse_id + 1)
    update_attribute(:wood, wood - Woodhouse.find(woodhouse_id).woodcost)
    update_attribute(:stone, stone - Woodhouse.find(woodhouse_id).stonecost)
    update_attribute(:iron, iron - Woodhouse.find(woodhouse_id).ironcost)
    
  end
  
  def upgrade_pit
    update_attribute(:pit_id, pit_id + 1)
    update_attribute(:wood, wood - Pit.find(pit_id).woodcost)
    update_attribute(:stone, stone - Pit.find(pit_id).stonecost)
    update_attribute(:iron, iron - Pit.find(pit_id).ironcost)
  end
  
  def upgrade_mine
    update_attribute(:mine_id, mine_id + 1)
    update_attribute(:wood, wood - Mine.find(mine_id).woodcost)
    update_attribute(:stone, stone - Mine.find(mine_id).stonecost)
    update_attribute(:iron, iron - Mine.find(mine_id).ironcost)
  end
  
  def upgrade_farm
    update_attribute(:farm_id, farm_id + 1)
    update_attribute(:wood, wood - Farm.find(farm_id).woodcost)
    update_attribute(:stone, stone - Farm.find(farm_id).stonecost)
    update_attribute(:iron, iron - Farm.find(farm_id).ironcost)
  
  end
  
  

end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  # GET /villages
  # GET /villages.xml
  def index
    @villages = Village.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @villages }
    end
  end

  # GET /villages/1
  # GET /villages/1.xml
  def show
    @village = Village.find(params[:id])
    @coords = Coordinates.where(:user_id => @village.user_id).first
    @coords.x = @village.x
    @coords.y = @village.y
    @coords.save
    @user = User.find(@village.user_id)
    @village.update_population
    @village.save
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @village }
    end
  end

  # GET /villages/new
  # GET /villages/new.xml
  def new
    @village = Village.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @village }
    end
  end

  # GET /villages/1/edit
  def edit
    @village = Village.find(params[:id])
  end

  # POST /villages
  # POST /villages.xml
  def create
    @village = Village.new(params[:village])
    if Village.last.nil?
     @village.x = 50
     @village.y = 50
    elsif Village.last == Village.first 
     @village.x = 50
     @village.y = 48
    else
      if Village.last.x <= 50
        random = rand(4)
        if random == 0
          @village.x = 100 - Village.last.x 
        elsif random == 1
          @village.x = Village.last.x - 1
        elsif random == 2
          @village.x = Village.last.x - 2
        elsif random == 3
          @village.x = Village.last.x - 3
        else
          @village.x = 100 - Village.last.x  - 4
        end
      else
        random = rand(4)
        if random == 0
          @village.x = 100 - Village.last.x
        elsif random == 1
          @village.x = Village.last.x + 1
        elsif random == 2
          @village.x = Village.last.x + 2
        elsif random == 3
          @village.x = Village.last.x + 3
        else
          @village.x = 100 - Village.last.x + 4
        end
      end
      
      if Village.last.y <= 50
        random = rand(4)
        if random == 0
          @village.y = 100 - Village.last.y
        elsif random == 1
          @village.y = Village.last.y - 1
        elsif random == 2
          @village.y = Village.last.y - 2
        elsif random == 3
          @village.y = Village.last.y - 3
        else
          @village.y = 100 - Village.last.y - 4
        end
      else
        random = rand(4)
        if random == 0
          @village.y = 100 - Village.last.y
        elsif random == 1
          @village.y = Village.last.y + 1
        elsif random == 2
          @village.y = Village.last.y + 2
        elsif random == 3
          @village.y = Village.last.y + 3
        else
          @village.y = 100 - Village.last.y + 4
        end
      end
    end
     @village.hq_id = 1
     @village.woodhouse_id = 1
     @village.mine_id = 1
     @village.pit_id = 1
     @village.depot_id = 1
     @village.farm_id = 1
     @village.wood = 120
     @village.stone = 120
     @village.iron = 120
     @village.user_id = current_user.id
        if @village.x == Village.where(:x => @village.x) && @village.x == Village.where(:y => @village.y)
          while @village.x == Village.where(:x => @village.x) && @village.x == Village.where(:y => @village.y)
            @village.x = @village.x + 1
            @village.y = @village.y - 1
          end
        else
        end
    respond_to do |format|
      if @village.save
        format.html { redirect_to(@village, :notice => 'Village was successfully created.') }
        format.xml  { render :xml => @village, :status => :created, :location => @village }
        @c = Coordinates.new(params[:coordinates])
        @c.x = @village.x
        @c.y = @village.y
        @c.user_id = @village.user_id
        @c.save
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @village.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /villages/1
  # PUT /villages/1.xml
  def update
    @village = Village.find(params[:id])

    respond_to do |format|
      if @village.update_attributes(params[:village])
        format.html { redirect_to(@village, :notice => 'Village was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @village.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /villages/1
  # DELETE /villages/1.xml
  def destroy
    @village = Village.find(params[:id])
    @village.destroy

    respond_to do |format|
      format.html { redirect_to(villages_url) }
      format.xml  { head :ok }
    end
  end
  
  def upgrade_hq
    @village = Village.find(params[:id])
    if @village.wood >= Hq.find(@village.hq_id).woodcost && @village.stone >= Hq.find(@village.hq_id).stonecost && @village.iron >= Hq.find(@village.hq_id).ironcost
    @village.upgrade_hq
    flash[:notice] = "Upgrading"
    redirect_to village_url(@village)
    else
    flash[:notice] = "Nicht genügend Rohstoffe!"
    redirect_to village_url(@village)
    end
  end
  
  def upgrade_depot
    @village = Village.find(params[:id])
    if @village.wood >= Depot.find(@village.depot_id).woodcost && @village.stone >= Depot.find(@village.depot_id).stonecost && @village.iron >= Depot.find(@village.depot_id).ironcost
    @village.upgrade_depot
    flash[:notice] = "Upgrading"
    redirect_to village_url(@village)
    else
    flash[:notice] = "Nicht genügend Rohstoffe!"
    redirect_to village_url(@village)
    end
  end
  
  def upgrade_woodhouse
    @village = Village.find(params[:id])
    @village.upgrade_woodhouse
    flash[:notice] = "Upgrading"
    redirect_to village_url(@village)
  end
  
  def upgrade_pit
    @village = Village.find(params[:id])
    @village.upgrade_pit
    flash[:notice] = "Upgrading"
    redirect_to village_url(@village)
  end
  
  def upgrade_mine
    @village = Village.find(params[:id])
    @village.upgrade_mine
    flash[:notice] = "Upgrading"
    redirect_to village_url(@village)
  end
  
  def upgrade_farm
    @village = Village.find(params[:id])
    @village.upgrade_farm
    flash[:notice] = "Upgrading"
    redirect_to village_url(@village)
  end
  
  def map
  end
  
  def up_to_top
    @village = Village.find(params[:id])
    @coordinates = Coordinates.where(:user_id => @village.user_id).first.y
    @coordinates = @coordinates + 4
    @village.up_to_top
    redirect_to village_url(@villages)
  end
  
  def ressources
    render :layout => false
    redirect_to
  end
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/_form.html.erb
<%= form_for(@village) do |f| %>
  <% if @village.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@village.errors.count, "error") %> prohibited this village from being saved:</h2>

      <ul>
      <% @village.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/villages/edit.html.erb
<h1>Editing village</h1>

<%= render 'form' %>

<%= link_to 'Show', @village %> |
<%= link_to 'Back', villages_path %>

app/views/villages/index.html.erb
<% if user_signed_in? %>
<h1>Deine Dörfer</h1>
<table>
<% @villages.each do |village| %>
  <tr>
    <td><%= link_to village.name, village %></td>
  </tr>
<% end %>
</table>
<% else %>
Du bist nicht eingeloggt
<% end %>

app/views/villages/new.html.erb
<h1>New village</h1>

<%= render 'form' %>

<%= link_to 'Back', villages_path %>

app/views/villages/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "navigation" >
  <table>
    <tr>
	  <td><%= link_to @user.name , user_path(@user) %> --- Dorf: <b> <%= @village.name %></b> ( <%= @village.x %>/<%= @village.y %> )</td><td></td>
	  <td>Wood: <font id="wood"><%= @village.wood %></font></td>
	  <td>Stone: <font id="stone"><%= @village.stone %></font> </td>
	  <td>Iron: <font id="iron"><%= @village.iron %> </font></td>
	  <td>Population: <font id="population"><%= @village.population %> </font>/ <font id="farm"><%= Farm.find(@village.farm_id).limit %></form></td>
	</tr>
  </table>
</div>

<table>

  <tr>
    <td><b>Gebäude</b></td><td><b>Stufe</b></td><td><b>Kosten(Holz/Stein/Eisen)</b></td>
  </tr>
  
  <tr>
    <td>Haupthaus:</td><td><%= @village.hq_id %></td><td><%= Hq.find(@village.hq_id).woodcost %> / <%= Hq.find(@village.hq_id).stonecost %> / <%= Hq.find(@village.hq_id).ironcost %></td><td><%= link_to "Bauen",  :controller => 'villages', :action => 'upgrade_hq' %></td>
  </tr> 
  
  <tr>
    <td>Lager:</td><td><%= @village.depot_id %></td><td><%= Depot.find(@village.depot_id).woodcost %> / <%= Depot.find(@village.depot_id).stonecost %> / <%= Depot.find(@village.depot_id).ironcost %></td><td><%= link_to "Bauen",  :controller => 'villages', :action => 'upgrade_depot' %></td>
  </tr>
  
  <tr>
    <td>Holzfäller:</td><td><%= @village.woodhouse_id %></td> <td><%= Woodhouse.find(@village.woodhouse_id).woodcost %> / <%= Woodhouse.find(@village.woodhouse_id).stonecost %> / <%= Woodhouse.find(@village.woodhouse_id).ironcost %></td><td><%= link_to "Bauen",  :controller => 'villages', :action => 'upgrade_woodhouse' %></td>
  </tr>
  
  <tr>
    <td>Steinbruch:</td><td><%= @village.pit_id %></td> <td><%= Woodhouse.find(@village.woodhouse_id).woodcost %> / <%= Woodhouse.find(@village.woodhouse_id).stonecost %> / <%= Woodhouse.find(@village.woodhouse_id).ironcost %></td><td><%= link_to "Bauen",  :controller => 'villages', :action => 'upgrade_pit' %></td>
  </tr>

  <tr>
    <td>Mine:</td><td><%= @village.mine_id %></td> <td><%= Mine.find(@village.mine_id).woodcost %> / <%= Mine.find(@village.mine_id).stonecost %> / <%= Mine.find(@village.mine_id).ironcost %></td><td><%= link_to "Bauen",  :controller => 'villages', :action => 'upgrade_mine' %></td>
  </tr>  

  <tr>
    <td>Farm:</td><td><%= @village.farm_id %></td><td><%= Farm.find(@village.farm_id).woodcost %> / <%= Farm.find(@village.farm_id).stonecost %> / <%= Farm.find(@village.farm_id).ironcost %></td><td><%= link_to "Bauen",  :controller => 'villages', :action => 'upgrade_farm' %></td>
  </tr> 
<br/>
</table>
<%= link_to 'Namen ändern', edit_village_path(@village) %>

app/views/villages/upgrade_hq.html.erb
asasasas