config/routes.rb
NewIsland::Application.routes.draw do

  resources :villages

  devise_for :users
  resources :users, :only => [:index, :show]
  resources :villages
  match "villages/:id/upgrade_hq" => 'villages#upgrade_hq', :controller => 'villages', :action => 'upgrade_hq'
  match "villages/:id/upgrade_depot" => 'villages#upgrade_depot', :controller => 'villages', :action => 'upgrade_depot'
  match "villages/:id/upgrade_woodhouse" => 'villages#upgrade_woodhouse', :controller => 'villages', :action => 'upgrade_woodhouse'
  match "villages/:id/upgrade_pit" => 'villages#upgrade_pit', :controller => 'villages', :action => 'upgrade_pit'
  match "villages/:id/upgrade_mine" => 'villages#upgrade_mine', :controller => 'villages', :action => 'upgrade_mine'
  match "villages/:id/upgrade_farm" => 'villages#upgrade_farm', :controller => 'villages', :action => 'upgrade_farm'
  match "coordinates/map" => 'coordinates#map', :controller => 'coordinates' 
  match "coordinates/up_to_top" => 'coordinates#up_to_top', :controller => 'coordinates', :action => 'up_to_top'
  match "coordinates/up_to_bottom" => 'coordinates#up_to_bottom', :controller => 'coordinates', :action => 'up_to_bottom'
  match "coordinates/up_to_right" => 'coordinates#up_to_right', :controller => 'coordinates', :action => 'up_to_right'
  match "coordinates/up_to_left" => 'coordinates#up_to_left', :controller => 'coordinates', :action => 'up_to_left'
  
  match "villages/:id/ressources" => 'villages#ressources', :controller => 'villages', :action => 'ressources'
root :to => "pages#home"
end

app/views/layouts/_header.html.erb
  <header>
    <nav>
      <ul>
        <center>
        <% if user_signed_in? %>
          <li> <%= link_to('Dörfer', villages_path) %></li>
          <li> <%= link_to('Karte', coordinates_map_path) %></li>
          <li> <%= link_to('Account', edit_user_registration_path) %></li>
  		  <li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
		<% else %>
		  <li><%= link_to "Startseite", root_path %></li>
		  <li><%= link_to('Registrieren', new_user_registration_path)  %> </li>
		  <li> <%= link_to('Login', new_user_session_path)  %> </li>
		<% end %>

        </center>
      </ul>
    </nav>

  </header>

app/views/layouts/_ressources.html.erb
<% if user_signed_in? %>
  <script>
  	var http = null;
	if (window.XMLHttpRequest) {
 	  http = new XMLHttpRequest();
	} 
	else if (window.ActiveXObject) {
 	  http = new ActiveXObject("Microsoft.XMLHTTP");
	}
	

	function ausgeben() {
 	  if (http.readyState == 4) {
        document.getElementById("Ausgabe").innerHTML =
        http.responseText;
 	  }	
	}






  var wood = 0 , stone = 0 , iron = 0 , population = 0, farm = 0;
  
  function initRessources(){
    wood = <%= @village.wood %> ;
    stone = <%= @village.stone %> ;
    iron = <%= @village.iron %> ;
    population = <%= @village.population %> ;
    farm = <%= Farm.find(@village.farm_id).limit %> ;
    updateRessources();
    
  }
  
  function updateRessources(){
    
      if (http != null) {
 	    http.open("GET", "ressources", true);
 	    http.onreadystatechange = ausgeben;
 	    http.send(null);
	  }
    
    document.getElementById("wood").innerHTML = wood;
    document.getElementById("stone").innerHTML = stone;
    document.getElementById("iron").innerHTML = iron;
    document.getElementById("population").innerHTML = population;
    document.getElementById("farm").innerHTML = farm;
    setTimeout("updateRessources()" , 1000);
  }
</script>

<% end %>

app/views/layouts/_test.html.erb
<script>
  var h = 1 , m = 1 , s = 1 ;
  
  function init(){
    s = <%= Time.now.sec %> ;
    m = <%= Time.now.min %> ;
    h = <%= Time.now.hour %> ;
    initRessources();
    updateTime();
  }
  
  function updateTime(){
    s++;
    if (s == 60 ){
      s = 0;
      m++;
    }
    if (m == 60){
      m = 0 ;
      h++;
    }
    
    if ( h == 24){
      h = 1;
    }
    document.getElementById("ur").innerHTML = h + ":" + m + ":" + s;
    setTimeout("updateTime()" , 1000);
  }
  
  
</script>

app/views/layouts/application.html.erb
<html>
<head>
  <title>NewIsland</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "test" %>
  <%= render 'layouts/test' %>
  <%= render 'layouts/ressources' %>
  <%= csrf_meta_tag %>
</head>
<body onload="init()">

<%= render 'layouts/header' %>
  <div class = "main">
     <section class = "round2">
    <p style="color: green"><%= notice %></p>
    <p style="color: red"><%= alert %></p>
    <%= yield %>
    <h6><font id="ur" size="2"></font></h6>
  </section>
</div>
</body>
</html>

<% if user_signed_in? %>
<div id="Ausgabe"></div>
<% else %>

<% end %>